[project]
name = "orbital-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lukasz", email = "153677792+LukPogo@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.16.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.5",
    "requests>=2.34.2",
    "scipy>=1.17.1",
]

[project.scripts]
orbital-sim = "orbital_sim:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
